name: 'build'

on:
  push:
    branches:
    - main
    - release-*

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.BRANCH }}
  
      - name: Notify
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: ${{ secrets.NOTIFY_URL }}
          method: POST
          data: "${{ github.repository }}"
          bearerToken: ${{ secrets.NOTIFY_TOKEN }}
          preventFailureOnNoResponse: true
          ignoreStatusCodes: true
          timeout: 60000
